config/routes.rb
ProyE::Application.routes.draw do
  resources :fronts

  root 'fronts#index'

end

app/models/front.rb
class Front < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fronts_controller.rb
class FrontsController < ApplicationController
  before_action :set_front, only: [:show, :edit, :update, :destroy]

  # GET /fronts
  # GET /fronts.json
  def index
    @fronts = Front.all
  end

  # GET /fronts/1
  # GET /fronts/1.json
  def show
  end

  # GET /fronts/new
  def new
    @front = Front.new
  end

  # GET /fronts/1/edit
  def edit
  end

  # POST /fronts
  # POST /fronts.json
  def create
    @front = Front.new(front_params)

    respond_to do |format|
      if @front.save
        format.html { redirect_to @front, notice: 'Front was successfully created.' }
        format.json { render action: 'show', status: :created, location: @front }
      else
        format.html { render action: 'new' }
        format.json { render json: @front.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fronts/1
  # PATCH/PUT /fronts/1.json
  def update
    respond_to do |format|
      if @front.update(front_params)
        format.html { redirect_to @front, notice: 'Front was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @front.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fronts/1
  # DELETE /fronts/1.json
  def destroy
    @front.destroy
    respond_to do |format|
      format.html { redirect_to fronts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_front
      @front = Front.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def front_params
      params[:front]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fronts_helper.rb
module FrontsHelper
end

app/views/fronts/_form.html.erb
<%= form_for(@front) do |f| %>
  <% if @front.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@front.errors.count, "error") %> prohibited this front from being saved:</h2>

      <ul>
      <% @front.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fronts/edit.html.erb
<h1>Editing front</h1>

<%= render 'form' %>

<%= link_to 'Show', @front %> |
<%= link_to 'Back', fronts_path %>

app/views/fronts/new.html.erb
<h1>New front</h1>

<%= render 'form' %>

<%= link_to 'Back', fronts_path %>

app/views/fronts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_front_path(@front) %> |
<%= link_to 'Back', fronts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Pruebas</title>
</head>
<body>

<div style="background-color: blue; width: 100%; height: 60px; text-align:center;"> <!-- Encabezado-->
  <h1 style="color: red; padding: 10px;">Titulo</h1> 
</div>
<!-- Fin Encabezado-->

<div style="background-color: azure; width: 100%; height: 80px; text-align:center; margin-top: 10px; font-size: 25px; padding-top: 30px; padding-left:200px;"><!-- Enlaces-->
  <a href="">Enlace1</a>
  <a href="">Enlace2</a>
  <a href="">Enlace3</a>
  <a href="">Enlace4</a>
</div><!-- Fin enlaces-->

<div style="background-color: aquamarine; margin-top: 30px"><!-- Cuerpo-->
  <table>
     <tr>
        <td>
            <div style="background-color: beige; width: 200px; max-height: 500px; padding: 10px 20px;"><!-- Resumen de lo que trata tu pagina-->
              t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum'
            </div><!--Fin Resumen de lo que trata tu pagina-->
        </td>
        <td>
          <div style="background-image: url(img01.jpg); width: 100%; height: 300px; color: white;"><!-- Contenido-->
          Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</div>
        </td><!-- Fin Contenido-->
     </tr>
  </table>
</div><!--Fin Cuerpo-->

     
<div style="background-color: floralwhite;"><!--Info-->
  <p>Tus datos</p>
  <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
</div><!--Fin Info-->
      
     

</body>
</html>